# -*- coding: utf-8 -*-
"""Untitled5.ipynb
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1nr_pafKV4Z6RID_GFDtW5LPPqV_b0BRw
"""

from fastapi import FastAPI, File, UploadFile
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from ultralytics import YOLO
from PIL import Image
import io
import torch
import uvicorn
import os
import gdown

app = FastAPI()

# Middleware agar bisa diakses dari frontend (CORS)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # bisa disesuaikan untuk keamanan
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

os.environ["HOME"] = "/app"

MODEL_PATH = "/tmp/my_final_model.pt"
GOOGLE_DRIVE_ID = "1-99E5Yac-279FwxmH0tKd_NCu5dHdCx7"  # ganti dengan ID kamu

if not os.path.exists(MODEL_PATH):
    print("Mengunduh model dari Google Drive...")
    # gdown.download(f"https://drive.google.com/uc?id={GOOGLE_DRIVE_ID}", MODEL_PATH, quiet=False)
    gdown.download(
        url=f"https://drive.google.com/uc?id={GOOGLE_DRIVE_ID}",
        output=MODEL_PATH,
        quiet=False,
        use_cookies=False  # ⬅️ ini penting
    )

recycle_messages = {
    "shoes": """Wah, kamu baru saja mengunggah gambar sepatu! 👟👠
Tahukah kamu? Sepatu bekas yang masih layak pakai sebaiknya tidak langsung dibuang. Ini beberapa hal yang bisa kamu lakukan:
✅ Gunakan kembali (reuse): Kalau masih bagus, berikan kepada adik atau teman yang membutuhkan.
♻ Daur ulang (recycle): Beberapa tempat menerima sepatu bekas untuk dijadikan bahan lapangan olahraga atau konstruksi.
🎨 Kreatif: Jadikan pot tanaman unik atau tempat alat berkebun mini yang lucu!
🌱 Dengan mengelola sepatu bekas dengan baik, kamu sudah membantu mengurangi sampah dan melindungi lingkungan. Keren!""",
    "bioligical": """Wah, kamu baru saja mengunggah gambar sampah organik! 🍌🍎
Tahukah kamu? Sampah organik seperti kulit buah dan sisa makanan bisa menjadi harta karun untuk tanaman! Ini yang bisa kamu lakukan:
✅ Gunakan kembali (reuse): Kulit pisang bisa jadi pupuk langsung untuk tanaman di rumah.
♻ Daur ulang (recycle): Ajak keluarga membuat kompos sederhana di halaman rumah.
🎨 Kreatif: Buat "bank sampah organik" dari botol bekas dan amati prosesnya!
🌱 Dengan mengolah sampah organik jadi kompos, kamu sudah membantu tanaman tumbuh subur. Hebat sekali!""",
    "glass": """Wah, kamu baru saja mengunggah gambar kaca! 🍶✨
Tahukah kamu? Kaca bisa didaur ulang berkali-kali tanpa kehilangan kualitasnya! Ini yang bisa kamu lakukan:
✅ Gunakan kembali (reuse): Botol kaca bisa jadi tempat pensil atau vas bunga cantik.
♻ Daur ulang (recycle): Kumpulkan dan bawa ke tempat pengumpulan kaca khusus.
🎨 Kreatif: Hias dengan tali warna-warni atau jadikan lampu tidur sederhana!
🌱 Satu botol kaca yang didaur ulang menghemat energi untuk menyalakan lampu 4 jam! Kamu sangat membantu bumi!""",
    "metal":"""Wah, kamu baru saja mengunggah gambar logam! 🥤⚙️
Tahukah kamu? Mendaur ulang logam menghemat energi hingga 95%! Ini yang bisa kamu lakukan:
✅ Gunakan kembali (reuse): Kaleng bekas bisa jadi tempat pensil atau pot tanaman kecil.
♻ Daur ulang (recycle): Logam sangat berharga untuk didaur ulang jadi barang baru.
🎨 Kreatif: Buat robot lucu atau hiasan mozaik dari tutup logam!
🌱 Dengan mendaur ulang satu kaleng, kamu menghemat energi untuk menonton TV 3 jam. Luar biasa!""",
    "trash":"""Wah, kamu baru saja mengunggah gambar sampah sulit daur ulang! 🗑️⚠️
Tahukah kamu? Sampah seperti bungkus permen dan sedotan plastik sulit sekali didaur ulang. Yang paling penting adalah menguranginya:
✅ Kurangi (reduce): Hindari barang sekali pakai seperti sedotan plastik dan sendok plastik.
♻ Ganti alternatif: Bawa tempat makan dan botol minum sendiri dari rumah.
🎨 Pilih bijak: Pilih snack dengan kemasan ramah lingkungan atau buat sendiri di rumah!
🌱 Dengan mengurangi sampah sulit daur ulang, kamu jadi pahlawan lingkungan sejati. Kamu luar biasa!""",
    "clothes":"""Wah, kamu baru saja mengunggah gambar pakaian! 👕👖
Tahukah kamu?
Pakaian yang sudah tidak dipakai sebaiknya tidak langsung dibuang ke tempat sampah biasa. Ini beberapa hal yang bisa kamu lakukan:
✅ Gunakan kembali (reuse): Kalau masih bagus, kamu bisa memakainya lagi atau memberikannya kepada orang yang membutuhkan.
 ♻️ Daur ulang (recycle): Ada tempat khusus yang menerima pakaian bekas untuk diubah menjadi bahan baru, seperti kain pel atau isian bantal.
 🎨 Kreatif: Kamu bisa memotong kainnya untuk dijadikan tas kecil, dompet, atau hiasan dinding!
🌱 Dengan tidak membuang pakaian sembarangan, kamu sudah membantu bumi tetap bersih dan sehat. Hebat!""",
    "paper":"""Kamu baru saja mengunggah gambar kertas! 📄✂️
Tahukah kamu?
Kertas bisa dengan mudah didaur ulang dan digunakan kembali. Tapi kita juga harus hati-hati agar tidak membuang kertas sembarangan.
Ini yang bisa kamu lakukan:
✅ Pisahkan kertas dari sampah basah, supaya tidak rusak dan bisa didaur ulang.
 🎨 Gunakan sisi kosongnya untuk menggambar atau mencatat.
 📦 Kumpulkan kertas bekas dan kirim ke tempat daur ulang, atau berikan ke bank sampah.
🌍 Kertas berasal dari pohon. Semakin banyak kita mendaur ulang, semakin banyak pohon yang bisa diselamatkan!""",
    "plastic":"""Kamu baru saja mengunggah gambar plastik! 🛍️🥤
Tahukah kamu?
Plastik sulit terurai dan bisa mencemari lingkungan selama ratusan tahun! Tapi jangan khawatir, kamu bisa membantu bumi dengan cara yang mudah:
✅ Gunakan ulang plastik seperti botol atau kantong belanja.
 🚮 Pisahkan sampah plastik dari yang lain, supaya mudah didaur ulang.
 🏫 Bawa tempat minum sendiri ke sekolah, supaya tidak beli botol plastik terus.
🌊 Banyak hewan laut yang sakit karena makan plastik. Yuk, kita bantu mereka dengan membuang plastik di tempat yang benar!""",
    "battery":"""Wah, kamu mengunggah gambar baterai!
Tahukah kamu?
Baterai bekas itu berbahaya, lho! Kalau dibuang sembarangan, bisa mencemari tanah dan air karena mengandung zat kimia beracun.
🛑 Jangan buang baterai ke tempat sampah biasa!
🟢 Apa yang harus kamu lakukan?
 ✅ Kumpulkan baterai bekas di wadah khusus.
 ✅ Minta bantuan orang tua atau guru untuk membawanya ke tempat penampungan baterai.
 ✅ Ingatkan teman-teman juga agar tidak membuang baterai sembarangan.
⚠️ Satu baterai kecil bisa mencemari ratusan liter air. Yuk, jadi pahlawan lingkungan dengan membuangnya di tempat yang benar!""",
    "cardboard":"""Keren! Kamu mengunggah gambar kardus.
Tahukah kamu?
Kardus itu bisa didaur ulang, lho! Daripada dibuang, lebih baik digunakan kembali atau dijual ke tempat daur ulang.
🟢 Apa yang bisa kamu lakukan dengan kardus?
 ✅ Gunakan lagi untuk menyimpan barang.
 ✅ Jadikan bahan kerajinan tangan, seperti rumah-rumahan atau tempat pensil!
 ✅ Lipat rapi dan kumpulkan untuk didaur ulang.
🎨 Dengan sedikit kreativitas, kardus bisa jadi mainan atau alat belajar yang seru!
🌱 Yuk, kurangi sampah dengan mendaur ulang kardus dan menjaga bumi tetap bersih!"""
}

# Load model kamu
model = YOLO(MODEL_PATH)

# Mapping label ke daftar link (banyak link per label)
recycle_links = {
    "cardboard": [
        "https://youtu.be/A5vDaQSpkSM?si=L2AET_5yspaZFrZc",
        "https://youtu.be/GIjS7Rv7lyg?si=Vq3dsDqUyR9J5Ia0",
        "https://youtu.be/rIAwV8ucvaY?si=FW037oACMD9O-Oq8",
        "https://youtu.be/-WPRaZ_SO9E?si=6owXGM-EjYcICoiP",
        "https://youtu.be/o4oQ1I7RYeg?si=iJGl4Tve2vEoBBHN",
        "https://youtu.be/T7I5arklM3o?si=Y8Tvz2XSbFXBxXhA",
        "https://youtu.be/t9qQRbz7ZIs?si=VK7c1ELIKBZFVZFA",
        "https://youtu.be/c-m-EpgpssM?si=-vIXTHjqTmPa8Ioq",
        "https://vt.tiktok.com/ZShwtUbU2/"
    ],
    "shoes": [
        "https://youtu.be/9Nv03-tKM5w?si=OSx5D5RA9LtMGOQt",
        "https://youtu.be/R85b3lxOKvY?si=jEDjEClsFPIA_E0p",
        "https://youtu.be/n86OX7b994U?si=uLG7qGsnwPmL5hxy",
        "https://youtu.be/8syHrV83sH4?si=CsoeKmWDHuBosUs-",
        "https://youtu.be/-ZDqXqeiKdA?si=1jhsAywORrUOVDVh",
        "https://youtu.be/ZuEQzhfdjUw?si=zby4laSYYh5dpJE-",
        "https://youtu.be/LtIeleKkLnM?si=KagopuDfBKc250Q6",
        "https://youtu.be/zw-Unekn1I8?si=HPgnHE9OoUmzseKn",
        "https://vt.tiktok.com/ZShwWkULG/"
    ],
    "biological": [
        "https://youtu.be/_hAv9wrPAvc?si=Ktg5z_a4aWMr9wj5",
        "https://youtu.be/Yu2rQlGTWfA?si=WRXQkXUxewEu4YNb",
        "https://youtu.be/wus8-Fkk_s8?si=QB7aKhq9fZfvNN2q",
        "https://youtu.be/YU9AzKf2ZFA?si=p42PzTTCp_QxVphW",
        "https://youtu.be/ftaxJ2C7LKA?si=tVcgE2OrYb63QQfD",
        "https://youtu.be/sZoa4ZrSkZ4?si=sRdnIL5s1Td2kEc5",
        "https://youtu.be/ol8CF1n29oA?si=7UpUW7yXVRS-kawk",
        "https://youtu.be/h1w4D6zbeKE?si=R86ygsiijbmI77Jv",
        "https://vt.tiktok.com/ZShEfgd8s/"
    ],
    "glass": [
        "https://youtu.be/Ny8Af_ADvtg?si=8fKN7ms8zrw541LV",
        "https://youtu.be/kZCpesLOuns?feature=shared",
        "https://youtu.be/Um2CBJXsGOo?si=ncY8YRnVeWJsg1fw",
        "https://youtu.be/L3LCG9ly0aM?si=MO_ntD2XFcjd_eeF",
        "https://youtu.be/O82eQHLG70k?si=eLkisKKxpBTeGnPK",
        "https://youtu.be/9FUG5ZZBCVk?si=70J14_llgywteeuz",
        "https://youtu.be/Ua3DuBXCU_A?si=ds-up2OpIdSINd6c",
        "https://vt.tiktok.com/ZShEPsBd9/"
    ],
    "metal": [
        "https://youtu.be/9do7RzfrXZ0?si=8QlAs623-oFaCnq_",
        "https://youtu.be/YUJf9dPKT-M?si=6nuf76T5vR8egSZQ",
        "https://youtu.be/WPvZEPnxUV4?si=mNTwdQzJyJAfO2XC",
        "https://youtu.be/V1SO4OSkGbk?si=6lDANB_3J5Xs3twi",
        "https://youtu.be/aHNeaA_BX1s?si=V-K7oJgXfgWmnNgm",
        "https://youtu.be/mkMZcqdyyXk?si=tpUynuz_lJA3HbU1",
        "https://youtu.be/SdCEEaeX2sk?si=B4qRIFeT6HW0l4zj",
        "https://youtu.be/HoYIos9pWMY?si=Bi4RtouMRbb0ha7H",
        "https://vt.tiktok.com/ZShE548Gp/"
    ],
    "trash": [
        "https://youtu.be/ogE3n_KdYfg?si=loCcrI0TtqxW5twh",
        "https://youtu.be/MJd3bo_XRaU?si=Y9lKJHhyIjvI2KcX",
        "https://youtu.be/WQCevNdGOUs?si=VKSOuDY9aebW7e_x",
        "https://youtu.be/Yv19QNLuMlc?si=Vj1nzXuCaTou4F_t",
        "https://youtu.be/ZyQ4ju-a9WM?si=UZ_sm2nEEhtlT76L",
        "https://youtu.be/T2Hu0fjuX5k?si=z6OMePdh8fvMkowY",
        "https://youtu.be/8YzK2gbuYnU?si=1Y2Xg0JUJc5LGfsn",
        "https://youtu.be/86VsLdF-cig?si=K0W2PBQCDj4_Djbq",
        "https://vt.tiktok.com/ZShEa4cTB/"
    ],
    "clothes": [
        "https://www.youtube.com/watch?v=H8KW1pfy95g",
        "https://www.youtube.com/watch?v=Vp12LHCB3vo",
        "https://www.youtube.com/watch?v=svUFkm0a9Ic",
        "https://www.youtube.com/watch?v=8JKpXxIpSys",
        "https://www.youtube.com/watch?v=rrO-xk4d0DA",
        "https://www.tiktok.com/@greenwelfare.id/video/7397408102569610502?q=DIY%20baju%20bekas&t=1748407898675"
    ],
    "paper": [
        "https://www.youtube.com/watch?v=Ydjg8pnJGqA",
        "https://www.youtube.com/watch?v=j1zXMpc-1As",
        "https://www.youtube.com/watch?v=rgh_hI712bI",
        "https://www.tiktok.com/@ricegrains_manual/video/7218887274853944618?q=DIY%20kertas&t=1748408475051",
        "https://www.tiktok.com/@katrinasartt/video/7486137444778249494?q=DIY%20kertas&t=1748408475051",
        "https://www.tiktok.com/@chellerodrigueez/video/7314762408684227846?q=DIY%20kertas&t=1748408475051"
    ],
    "plastic": [
        "https://www.youtube.com/watch?v=ogE3n_KdYfg&pp=ygUQRElZIGtlcnRhcyBiZWthc9IHCQmwCQGHKiGM7w%3D%3D",
        "https://www.youtube.com/watch?v=k1jVoQ1tKAI&pp=ygUQRElZIGtlcnRhcyBiZWthcw%3D%3D",
        "https://www.youtube.com/watch?v=KDuX9siPT6U",
        "https://www.youtube.com/watch?v=VBvwdSC0POU",
        "https://www.youtube.com/watch?v=Xs2hAWuPmSg",
        "https://www.tiktok.com/@listatsurayya/video/7468523949735857413?q=DIY%20plastik&t=1748408984145",
        "https://www.tiktok.com/@derya.tavas/video/7336981410504363297?q=DIY%20plastik&t=1748408984145"
    ],
    "battery": [
        "https://www.youtube.com/watch?v=D7td95ySam8",
        "https://www.youtube.com/watch?v=EqD8iW97p9Q",
        "https://www.youtube.com/watch?v=tWfX2e-kKrU"
    ]
}

@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    image_bytes = await file.read()
    image = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    results = model(image)
    probs = results[0].probs.data

    topk = torch.topk(probs, k=2)
    indices = topk.indices
    values = topk.values

    top_confidence = float(values[0]) * 100

    predictions = []
    if top_confidence >= 85:
        indices = indices[:1]
    
    for idx in indices:
        label = results[0].names[idx.item()]
        confidence = float(probs[idx]) * 100
        links = recycle_links.get(label, ["https://example.com/default"])
        predictions.append({
            "label": label,
            "confidence": round(confidence, 2),
            "recycle_links": links,
            "message": recycle_messages.get(label, "Belum ada informasi pengelolaan untuk sampah ini.")
        })

    return JSONResponse(content={"top_predictions": predictions})

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=7860)
